# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='date', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='time', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(default='dob', max_length=255),
            preserve_default=False,
        ),
    ]
